# PIPELINE DEFINITION
# Name: data-images
# Inputs:
#    data_images__params: dict [Default: {'image_root_dir': '', 'transform_variable': 'transform', 'path': '', 'data_transform_path': '', 'shuffle': False, 'batch_size': 4.0, 'target': '', 'safe_libraries': 'torchvision'}]
# Outputs:
#    Output: str
#    output: system.Dataset
components:
  comp-data-images:
    executorLabel: exec-data-images
    inputDefinitions:
      parameters:
        data_images__params:
          defaultValue:
            batch_size: 4.0
            data_transform_path: ''
            image_root_dir: ''
            path: ''
            safe_libraries: torchvision
            shuffle: false
            target: ''
            transform_variable: transform
          isOptional: true
          parameterType: STRUCT
    outputDefinitions:
      artifacts:
        output:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
      parameters:
        Output:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-data-images:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - data_images
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'mammoth-commons[deployment]'\
          \ 'torch' 'torchvision' 'pandas' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: mammotheu/data_images:v0024
pipelineInfo:
  name: data-images
root:
  dag:
    outputs:
      artifacts:
        output:
          artifactSelectors:
          - outputArtifactKey: output
            producerSubtask: data-images
      parameters:
        Output:
          valueFromParameter:
            outputParameterKey: Output
            producerSubtask: data-images
    tasks:
      data-images:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-images
        inputs:
          parameters:
            data_images__params:
              componentInputParameter: data_images__params
        taskInfo:
          name: data-images
  inputDefinitions:
    parameters:
      data_images__params:
        defaultValue:
          batch_size: 4.0
          data_transform_path: ''
          image_root_dir: ''
          path: ''
          safe_libraries: torchvision
          shuffle: false
          target: ''
          transform_variable: transform
        isOptional: true
        parameterType: STRUCT
  outputDefinitions:
    artifacts:
      output:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    parameters:
      Output:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
