# PIPELINE DEFINITION
# Name: hercules
# Inputs:
#    data_csv__params: dict
#    model_onnx__params: dict
#    new_metric__params: dict
#    sensitive_attributes: list
components:
  comp-data-csv:
    executorLabel: exec-data-csv
    inputDefinitions:
      parameters:
        data_csv__params:
          defaultValue: {}
          isOptional: true
          parameterType: STRUCT
    outputDefinitions:
      artifacts:
        loaded_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-model-onnx:
    executorLabel: exec-model-onnx
    inputDefinitions:
      parameters:
        model_onnx__params:
          defaultValue: {}
          isOptional: true
          parameterType: STRUCT
    outputDefinitions:
      artifacts:
        loaded_model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
  comp-new-metric:
    executorLabel: exec-new-metric
    inputDefinitions:
      artifacts:
        csv_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        onnx_model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
      parameters:
        new_metric__params:
          defaultValue: {}
          isOptional: true
          parameterType: STRUCT
        sensitive_attributes:
          parameterType: LIST
    outputDefinitions:
      artifacts:
        report:
          artifactType:
            schemaTitle: system.Markdown
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-data-csv:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - data_csv
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'fairbench' 'numpy'\
          \ 'pandas' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: mammotheu/loader_csv_fairdemo:v010
    exec-model-onnx:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - model_onnx
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'onnxruntime'\
          \ 'numpy' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: mammotheu/loader_model_fairdemo:v010
    exec-new-metric:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - new_metric
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'fairbench' 'onnxruntime'\
          \ 'numpy' 'pandas' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: mammotheu/metric_fairdemo:v010
pipelineInfo:
  name: hercules
root:
  dag:
    tasks:
      data-csv:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-csv
        inputs:
          parameters:
            data_csv__params:
              componentInputParameter: data_csv__params
        taskInfo:
          name: data-csv
      model-onnx:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-model-onnx
        inputs:
          parameters:
            model_onnx__params:
              componentInputParameter: model_onnx__params
        taskInfo:
          name: model-onnx
      new-metric:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-new-metric
        dependentTasks:
        - data-csv
        - model-onnx
        inputs:
          artifacts:
            csv_dataset:
              taskOutputArtifact:
                outputArtifactKey: loaded_dataset
                producerTask: data-csv
            onnx_model:
              taskOutputArtifact:
                outputArtifactKey: loaded_model
                producerTask: model-onnx
          parameters:
            new_metric__params:
              componentInputParameter: new_metric__params
            sensitive_attributes:
              componentInputParameter: sensitive_attributes
        taskInfo:
          name: new-metric
  inputDefinitions:
    parameters:
      data_csv__params:
        parameterType: STRUCT
      model_onnx__params:
        parameterType: STRUCT
      new_metric__params:
        parameterType: STRUCT
      sensitive_attributes:
        parameterType: LIST
schemaVersion: 2.1.0
sdkVersion: kfp-2.7.0
