id: data_image_pairs
name: data image pairs
description: "\nLoads image pairs declared in a CSV file.\nThe expected format is\
  \ to have the first image's identifier in the first column,\nand the second image's\
  \ identifier in the second column, Sensitive attributes\ncan be selected from the\
  \ rest of the columns. The images identifiers read from the columns\nare transformed\
  \ to loading paths by string specifications that can contain the\nsymbols: {root}\
  \ to refer to the root directory, {col} to refer to the column name, and {id}\n\
  to refer to the column entry.\n\nArgs:\n    path: The path to the CSV file containing\
  \ information about the dataset.\n    image_root_dir: The root directory where the\
  \ actual image files are stored.\n    target: Indicates the predictive attribute\
  \ in the dataset.\n    data_transform: A path or implementation of a torchvision\
  \ data transform.\n    batch_size: The number of image pairs in each batch.\n  \
  \  shuffle: Whether to shuffle the dataset.\n    data_transform_path: A path or\
  \ implementation of a torchvision data transform. Alternatively, paste the transformation\
  \ code here.\n    transform_variable: The transformation target variable that should\
  \ be extracted after the namesake code runs.\n    num_workers: Number of subprocesses\
  \ to use for data loading.\n    safe_libraries: A comma-separated list of safe libraries\
  \ that are allowed in the transformation code. As a safety measure against code\
  \ injection attacks, an error will be created if libraries other than those are\
  \ encountered.\n"
parameter_info: Some parameters are needed.
component_type: LOADER_DATA
parameter_default:
  path: ''
  image_root_dir: ./
  target: ''
  batch_size: 4
  shuffle: false
  data_transform_path: ''
  transform_variable: transform
  num_workers: 0
  safe_libraries: numpy,torch,torchvision,PIL,io,requests,urllib
output_types:
- ImageLike
- ImagePairs
