id: data_images
name: data images
description: "\n    Creates a Dataset for loading image data from a CSV file.\n\n\
  \    Args:\n        path (str): The path to the CSV file containing information\
  \ about the dataset.\n        root_dir (str): The root directory where the actual\
  \ image files are stored.\n        target (str): Indicates the predictive attribute\
  \ in the dataset.\n        data_transform (str): A path or implementation of a torchvision\
  \ data transform.\n    Returns:\n        Image dataset.\n    "
parameter_info: Some parameters are needed.
component_type: LOADER_DATA
parameter_default:
  path: ''
  root_dir: ./
  target: ''
  data_transform: ''
  batch_size: 4
  shuffle: false
input_types: []
output_types:
- Image
